# Generated by Django 2.2.3 on 2019-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190715_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='displayed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
